language: c

sudo: required

group: travis_latest

jobs:
  include:
    - name: Linux Build
      os: linux
      dist: bionic

    - name: MacOS Build
      os: osx
      osx_image: xcode10.2

cache:
  ccache: true

script:
  - cd "${TRAVIS_BUILD_DIR}"/tests
  - python3 tester.py testset_travis.json
