sudo: required

cache:
  ccache: true


jobs:
  include:
    - name: "Linux AMD64 build"
      arch: amd64
      os: linux
      dist: bionic
      group: travis_latest
      language: python
      python: "3.6"
      addons:
        apt:
          packages:
          - libblas-dev
          - liblapack-dev
          - bc
      script:
        - cd "${TRAVIS_BUILD_DIR}"/tests
        - pip install jinja2
        - python tester.py testset_travis_blasfeo_double_amd64.json
        - python tester.py testset_travis_blas_double_amd64.json
        - python tester.py testset_travis_blas_single_amd64.json

    - name: "Linux ARM64 build"
      arch: arm64
      os: linux
      dist: bionic
      group: travis_latest
      language: python
      python: "3.6"
      addons:
        apt:
          packages:
          - libblas-dev
          - liblapack-dev
          - bc
      script:
        - cd "${TRAVIS_BUILD_DIR}"/tests
        - pip install jinja2
        - python tester.py testset_travis_blasfeo_double_arm64.json
        - python tester.py testset_travis_blas_double_arm64.json
        - python tester.py testset_travis_blas_single_arm64.json
