language: c

sudo: required

group: travis_latest

jobs:
  include:
    - name: Linux Build
      os: linux
      dist: bionic

    - name: MacOS Build 10.2
      os: osx
      osx_image: xcode10.2


python:
  - "3.6"

install:
  - pip3 install --user jinja2

cache:
  ccache: true

script:
  - cd "${TRAVIS_BUILD_DIR}"/tests
  - python3 tester.py testset_travis.json
